Dump structure.sql with Rails 8.1
This was produced with the app set up locally without govuk-docker and
with postgres 14, which matches our deployed environments, using `bundle
exec rake db:schema:dump`

When running via govuk-docker and postgres 17 (per the
docker-compose.yml file), it also makes the following changes

```
SET transaction_timeout = 0;
```

```
--
-- Name: content_items_import; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_items_import (
    data jsonb
);
```

The former also gets added when switching to postgres 14 in the
docker-compose.yml. However, this parameter is not available in postgres
14 and can cause an error per the log below, so I'm omitting it. I'm
also omitting the latter since it only appears in the definitely
postgres 17 scenario

```
ERROR:  unrecognized configuration parameter "transaction_timeout"
```